dist: trusty

language: node_js
node_js:
  - 12
cache:
  directories:
    - ./functions/node_modules
script:
  - yarn global add codecov
  - cd functions
  - npm install
  - npm run report-coverage
  - npm run build
  - cd ../front
  - npm install
  - npm run report-coverage
  - npm test:unit
  - npm run build
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_FUNCTIONS_TOKEN$
after_success:
  - yarn global add firebase-tools
  - firebase deploy --token "$FIREBASE_FUNCTIONS_TOKEN"
  - codecov