dist: xenial

language: node_js
node_js:
  - 12
  - v14.2.0
cache:
  directories:
    - ./functions/node_modules
    - ./front/node_modules
script:
  - yarn global add codecov
  - npm install -g @vue/cli
  - cd functions
  - rm package-lock.json
  - npm install
  - npm run build
  - cd ../
  - echo "Now going on to build Vue 3."
  - cd front
  - rm package-lock.json
  - npm install
  - npm run build
  - cd ../
  - cd functions
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_FUNCTIONS_TOKEN$
after_success:
  - yarn global add firebase-tools
  - firebase deploy --token "$FIREBASE_FUNCTIONS_TOKEN"
  - codecov